Repository codestates/weSeason-client, pull requests merged in 2021-02, with the labels that each got.

#81 [Client] #80 / https, html, favicon, 리덕스 툴킷 설치
  new/.gitignore
  new/package-lock.json
  new/package.json
  new/public/favicon.ico
  new/public/favicon.png
  new/public/index.html
  new/src/App.tsx
Labels: E:0.5, Refactoring, client

#82 [Client] #80 / old 파일을 수정했습니다.
  old/.eslintcache
  old/package-lock.json
Labels: Refactoring

#83 [Client] #74 / 회원가입 페이지 반응형 레이아웃 css 구현, 폰트 폴더 추가, 리덕스 툴킷 설치
  new/package-lock.json
  new/package.json
  new/src/App.tsx
  new/src/Components/signup/SignUp.tsx
  new/src/Components/signup/signUp.css
  new/src/fonts/AppleSDGothicNeoB.ttf
  new/src/fonts/AppleSDGothicNeoEB.ttf
  new/src/fonts/AppleSDGothicNeoH.ttf
  new/src/fonts/AppleSDGothicNeoL.ttf
  new/src/fonts/AppleSDGothicNeoM.ttf
  new/src/fonts/AppleSDGothicNeoR.ttf
  new/src/fonts/AppleSDGothicNeoSB.ttf
  new/src/fonts/AppleSDGothicNeoT.ttf
  new/src/fonts/AppleSDGothicNeoUL.ttf
  new/src/fonts/Jalnan.ttf
  new/src/index.tsx
  new/src/reducers/appReducer.tsx
Labels: E:3, Refactoring, client

#85 [client] #75 / 회원가입 페이지 구조 변경, 상세 css 구현
  new/package-lock.json
  new/package.json
  new/src/App.tsx
  new/src/Components/signup/SignUp.tsx
  new/src/Components/signup/UserInfo.tsx
  new/src/Components/signup/infoData.ts
  new/src/Components/signup/signUp.css
  new/src/const.ts
  new/src/index.tsx
  new/src/reducers/appReducer.tsx
  new/src/reducers/userInfoReducer.ts
Labels: E:3, Refactoring, client

#87 [Client] #86 / 회원가입__ajax, 웹용 에러 모달, 태블릿/모바일 용 에러 노출 구현
  new/package-lock.json
  new/package.json
  new/src/App.tsx
  new/src/Components/login/Login.tsx
  new/src/Components/modal/OneBtnModal.css
  new/src/Components/modal/OneBtnModal.tsx
  new/src/Components/signup/SignUp.tsx
  new/src/Components/signup/signUp.css
  new/src/index.tsx
  new/src/reducers/pageWidthReducer.ts
Labels: E:3, Refactoring, client

#89 [Client] #88 / 모바일, 태블릿 모달 비노출 및 상태 관리
  new/src/Components/modal/OneBtnModal.css
  new/src/Components/signup/SignUp.tsx
  new/src/Components/signup/signUp.css
Labels: E:3, Refactoring, client

#90 [Client] #70/ login 페이지 웹버전 레이아웃, css 구현
  new/src/Components/login/Login.tsx
  new/src/Components/login/login.css
Labels: E:3, Refactoring

#93 [client] #72 / 회원정보 수정하기
  new/package-lock.json
  new/src/App.tsx
  new/src/Components/login/Login.tsx
  new/src/Components/login/login.css
  new/src/Components/mypage/AskWithdrawalContent.tsx
  new/src/Components/mypage/CheckPasswordContent.tsx
  new/src/Components/mypage/ErrorContent.tsx
  new/src/Components/mypage/Modal.tsx
  new/src/Components/mypage/MyPage.tsx
  new/src/Components/signup/SignUp.tsx
  new/src/api/index.ts
  new/src/index.tsx
  new/src/reducers/appReducer.ts
  new/src/reducers/index.ts
  new/src/reducers/mypageReducer.ts
  old/.eslintcache
Labels: E:3, Refactoring, client, high

#95 [Client] #70~71 / 로그인 페이지 반응형 구현 / 로컬 로그인 기능 구현 / 엑세스 토큰 상태 저장
  new/src/App.tsx
  new/src/Components/login/Login.tsx
  new/src/Components/login/login.css
  new/src/Components/modal/OneBtnModal.tsx
  new/src/Components/signup/SignUp.tsx
  new/src/Components/signup/signUp.css
  new/src/index.tsx
  new/src/reducers/accessTokenReducer.ts
Labels: E:3, Refactoring

#96 [client] 중복 리듀서 삭제, 파일 구조 변경에 따른 충돌 수정
  new/src/Components/login/Login.tsx
  new/src/index.tsx
  new/src/reducers/accessTokenReducer.ts
Labels: E:3, Refactoring, client

#97 [Client] #수정 / pageWidth 상태 로직 변경, 프로미스 사용 타입 변경
  new/src/App.tsx
  new/src/Components/login/Login.tsx
  new/src/Components/signup/SignUp.tsx
  new/src/reducers/pageWidthReducer.ts
Labels: Refactoring

#98 [Client] #94 / 로그인__ oauth 구글, 깃허브 연결
  new/src/Components/login/Login.tsx
  new/src/Components/login/login.css
  new/src/Components/signup/SignUp.tsx
  new/src/Components/signup/signUp.css
  new/src/reducers/pageWidthReducer.ts
Labels: E:3, Refactoring, client

#102 [client] Add: main / Modify: signUp fault password check
  new/src/App.tsx
  new/src/Components/main/Main.tsx
  new/src/Components/main/clothes/ClothesBox.tsx
  new/src/Components/main/clothes/ClothesItem.tsx
  new/src/Components/main/clothes/ClothesList.tsx
  new/src/Components/main/clothes/clothesBox.css
  new/src/Components/main/clothes/clothesList.css
  new/src/Components/main/main.css
  new/src/Components/signup/SignUp.tsx
  new/src/images/background/first-main.jpeg
  new/src/images/background/sub-main.jpeg
  new/src/images/icon/btn-icon.png
  new/src/images/icon/clothes-icons/7부바지.png
  new/src/images/icon/clothes-icons/긴바지.png
  new/src/images/icon/clothes-icons/니트.png
  new/src/images/icon/clothes-icons/두꺼운코트.png
  new/src/images/icon/clothes-icons/린넨옷.png
  new/src/images/icon/clothes-icons/목도리.png
  new/src/images/icon/clothes-icons/민소매.png
  new/src/images/icon/clothes-icons/바람막이.png
  new/src/images/icon/clothes-icons/반바지.png
  new/src/images/icon/clothes-icons/반팔.png
  new/src/images/icon/clothes-icons/발열내의.png
  new/src/images/icon/clothes-icons/블라우스.png
  new/src/images/icon/clothes-icons/셔츠.png
  new/src/images/icon/clothes-icons/얇은재킷.png
  new/src/images/icon/clothes-icons/원피스.png
  new/src/images/icon/clothes-icons/장갑.png
  new/src/images/icon/clothes-icons/재킷.png
  new/src/images/icon/clothes-icons/짧은치마.png
  new/src/images/icon/clothes-icons/청바지.png
  new/src/images/icon/clothes-icons/청자켓.png
  new/src/images/icon/clothes-icons/캐시미어코트.png
  new/src/images/icon/clothes-icons/트렌치코트.png
  new/src/images/icon/clothes-icons/패딩.png
  new/src/images/icon/clothes-icons/항공점퍼.png
  new/src/images/icon/clothes-icons/후드.png
  new/src/images/icon/cloud-computing (3).png
Labels: Refactoring, client

#104 [client] #73/mypage UI
  new/src/App.tsx
  new/src/Components/login/Login.tsx
  new/src/Components/login/login.css
  new/src/Components/modal/OneBtnModal.css
  new/src/Components/modal/OneBtnModal.tsx
  new/src/Components/mypage/CheckPasswordContent.tsx
  new/src/Components/mypage/ErrorContent.tsx
  new/src/Components/mypage/Modal.tsx
  new/src/Components/mypage/MyPage.tsx
  new/src/Components/mypage/modal.css
  new/src/Components/mypage/mypage.css
  new/src/Components/signup/SignUp.tsx
  new/src/Components/signup/signUp.css
  new/src/api/auth/index.ts
  new/src/api/index.ts
  new/src/api/user/index.ts
  new/src/index.css
  new/src/index.tsx
  new/src/reducers/appReducer.ts
  new/src/reducers/mypageReducer.ts
  old/.eslintcache
Labels: E:3, Refactoring, client, high

#105 [client] #73 Finish mypage
  new/src/App.tsx
  new/src/Components/mypage/MyPage.tsx
  new/src/Components/mypage/modal.css
  new/src/Components/mypage/mypage.css
Labels: E:3, Refactoring, client, high

#106 [client] #69 add menu
  new/src/App.tsx
  new/src/Components/menu/Menu.tsx
  new/src/Components/menu/Nav.tsx
  new/src/Components/menu/menu.css
  new/src/Components/mypage/modal.css
  new/src/Components/mypage/mypage.css
  new/src/app.css
  new/src/index.css
  new/src/reducers/index.ts
  new/src/reducers/menuReducer.ts
  new/src/reducers/mypageReducer.ts
Labels: E:3, Refactoring, client, high

#107 [client] #69 / Add mobile menu finish
  new/src/Components/menu/Menu.tsx
  new/src/Components/menu/Nav.tsx
  new/src/Components/menu/menu.css
  new/src/Components/mypage/mypage.css
Labels: E:3, Refactoring, client, high

#108 [client] #76/ Add withdrawal
  new/src/App.tsx
  new/src/Components/mypage/AskWithdrawalContent.tsx
  new/src/Components/mypage/CheckPasswordContent.tsx
  new/src/Components/mypage/MyPage.tsx
  new/src/Components/withdrawl/Withdrawl.tsx
  new/src/Components/withdrawl/withdrawal.css
  new/src/api/user/index.ts
  new/src/reducers/mypageReducer.ts
Labels: E:3, Refactoring, client, high

#109 [client] #66 / Add main weather
  new/src/App.tsx
  new/src/Components/main/Main.tsx
  new/src/Components/main/weather/Weather.tsx
  new/src/Components/main/weather/WeatherBox.tsx
  new/src/Components/main/weather/WeatherItem.tsx
  new/src/Components/main/weather/weather.css
  new/src/Components/mypage/MyPage.tsx
  new/src/Components/mypage/modal/Modal.tsx
  new/src/Components/mypage/modal/content/AskWithdrawalContent.tsx
  new/src/Components/mypage/modal/content/CheckPasswordContent.tsx
  new/src/Components/mypage/modal/content/ErrorContent.tsx
  new/src/Components/mypage/modal/modal.css
  new/src/Components/mypage/withdrawl/Withdrawl.tsx
  new/src/Components/mypage/withdrawl/withdrawal.css
  new/src/api/auth/index.ts
  new/src/api/user/index.ts
  new/src/api/weather/index.ts
  new/src/index.css
  new/src/reducers/index.ts
  new/src/reducers/weatherReducer.ts
Labels: E:3, Refactoring, client, high

#110 [Client] #67 / #103 / clothesList 완료, clothesBox 반응형 구현, 회원가입 비밀번호 체크 조건문 수정
  new/src/App.tsx
  new/src/Components/main/Main.tsx
  new/src/Components/main/clothes/ClothesBox.tsx
  new/src/Components/main/clothes/ClothesItem.tsx
  new/src/Components/main/clothes/clothesBox.css
  new/src/Components/main/clothes/clothesItem.css
  new/src/Components/main/clothes/clothesList.css
  new/src/Components/main/clothes/iconList.ts
  new/src/Components/modal/SearchVillage.tsx
  new/src/Components/signup/SignUp.tsx
  new/src/images/icon/cloud.png
Labels: E:3, Refactoring, client

#113 [client] #112/ Modify UI
  new/src/Components/main/weather/Weather.tsx
  new/src/Components/main/weather/WeatherBox.tsx
  new/src/Components/main/weather/weather.css
  new/src/Components/menu/menu.css
  new/src/Components/mypage/modal/modal.css
  new/src/Components/mypage/mypage.css
  new/src/Components/mypage/withdrawl/Withdrawl.tsx
  new/src/Components/mypage/withdrawl/withdrawal.css
  new/src/images/icon/cloud2_illustration_style2.png
Labels: E:3, Refactoring, client, high

#114 [Client] #111 / ClothesItem 애니메이션 구현, 로그인 / 회원가입 태블릿 UI 수정, ClothesList 스크롤 추가
  new/src/Components/login/login.css
  new/src/Components/main/Main.tsx
  new/src/Components/main/clothes/ClothesItem.tsx
  new/src/Components/main/clothes/ClothesList.tsx
  new/src/Components/main/clothes/clothesItem.css
  new/src/Components/main/clothes/clothesList.css
  new/src/Components/signup/signUp.css
Labels: E:3, Refactoring, client

#115 [Client] #68 / 동네 검색 모달 구현 완료 , geolocation 리듀서 구현,
  new/public/index.html
  new/src/App.tsx
  new/src/Components/main/Main.tsx
  new/src/Components/main/clothes/ClothesBox.tsx
  new/src/Components/main/clothes/clothesItem.css
  new/src/Components/main/clothes/clothesList.css
  new/src/Components/main/main.css
  new/src/Components/modal/SearchVillage.tsx
  new/src/Components/modal/searchVillage.css
  new/src/index.css
  new/src/reducers/index.ts
  new/src/reducers/locationReducer.ts
Labels: E:3, Refactoring, client

#116 [Client] #68 / Weather Location 리덕스 상태 이용 로직으로 수정
  new/src/Components/main/weather/Weather.tsx
Labels: E:3, Refactoring, client

#120 [client] #119/ Add logout, recommend clothes
  new/src/App.tsx
  new/src/Components/login/Login.tsx
  new/src/Components/main/Main.tsx
  new/src/Components/main/clothes/ClothesBox.tsx
  new/src/Components/main/weather/Weather.tsx
  new/src/Components/main/weather/WeatherItem.tsx
  new/src/Components/menu/Nav.tsx
  new/src/Components/menu/menu.css
  new/src/Components/signup/SignUp.tsx
  new/src/api/auth/index.ts
  new/src/api/clothes/index.ts
  new/src/api/user/index.ts
  new/src/reducers/weatherReducer.ts
Labels: E:3, Refactoring, client, high

#122 [Client] 전체 컴포넌트 상세 디테일 css 수정 1차
  new/src/App.tsx
  new/src/Components/main/clothes/clothesBox.css
  new/src/Components/main/clothes/clothesItem.css
  new/src/Components/main/weather/weather.css
  new/src/Components/menu/Menu.tsx
  new/src/Components/menu/menu.css
  new/src/Components/modal/SearchVillage.tsx
  new/src/Components/mypage/modal/content/CheckPasswordContent.tsx
  new/src/Components/mypage/modal/modal.css
  new/src/Components/mypage/mypage.css
  new/src/Components/signup/SignUp.tsx
  new/src/app.css
  new/src/images/icon/hambuger-menu.png
  new/src/images/icon/webMenu.png
Labels: E:3, Refactoring, client

#124 [Client] #118 #121 / 전체 세부 css 통일화 및 2차 수정, 일부 버그 수정
  new/src/Components/login/Login.tsx
  new/src/Components/login/login.css
  new/src/Components/main/clothes/ClothesBox.tsx
  new/src/Components/main/clothes/ClothesItem.tsx
  new/src/Components/main/clothes/clothesItem.css
  new/src/Components/main/clothes/clothesList.css
  new/src/Components/menu/menu.css
  new/src/Components/modal/SearchVillage.tsx
  new/src/Components/mypage/modal/modal.css
  new/src/Components/mypage/mypage.css
  new/src/Components/signup/signUp.css
  new/src/images/icon/hambuger-menu 2.png
  new/src/images/icon/webMenu 2.png
Labels: E:3, Refactoring, bug, client

#125 [Client] #118 / 메뉴 토글 내 로그아웃 모바일, 태블릿 버전 수정
  new/src/Components/menu/menu.css
Labels: E:3, Refactoring, client

#127 [client] #118 / 메인 height 수정, 소셜로그인 수정
  new/package-lock.json
  new/package.json
  new/src/App.tsx
  new/src/Components/main/Main.tsx
  new/src/Components/main/main.css
Labels: E:3, Refactoring, client

#129 [Client] 동네 검색 모달, 옷추천 받기 버그 수정, 구글 로그인 연동
  new/src/App.tsx
  new/src/Components/login/Login.tsx
  new/src/Components/main/Main.tsx
  new/src/Components/main/clothes/ClothesBox.tsx
  new/src/Components/main/main.css
  new/src/Components/main/weather/weather.css
  new/src/Components/modal/SearchVillage.tsx
  new/src/app.css
  new/src/reducers/locationReducer.ts
Labels: E:3, Refactoring, client

#132 [Client] #123 / 깃허브 소셜 로그인 연동 처리
  .DS_Store
  new/src/Components/main/Main.tsx
Labels: E:3, Refactoring, client

#134 [Client] 일부 any 타입 지정 코드를 수정했습니다.
  .DS_Store
  new/src/App.tsx
  new/src/Components/login/Login.tsx
  new/src/Components/main/Main.tsx
  new/src/Components/main/clothes/ClothesItem.tsx
  new/src/Components/main/clothes/ClothesList.tsx
  new/src/Components/main/clothes/iconList.ts
  new/src/Components/modal/OneBtnModal.tsx
  new/src/Components/modal/SearchVillage.tsx
  new/src/Components/signup/UserInfo.tsx
  new/src/api/user/index.ts
  new/src/api/weather/index.ts
  new/src/app.css
  new/src/index.tsx
  new/src/reducers/appReducer.ts
  new/src/reducers/locationReducer.ts
  new/src/reducers/pageWidthReducer.ts
  new/src/reducers/userInfoReducer.ts
Labels: E:3, Refactoring, client
